lr: 0.1
seed: 42
model_id: "resnet18"
epochs: 25
unfreeze_epoch: 5 # The epoch at which to unfreeze the backbone. Set to 0 to disable.
train_batch_size: 2048
test_batch_size: 4096
num_workers: 16
use_torch_compile: false